/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pasgenerator;

import java.awt.FileDialog;
import java.util.Random;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import static pasgenerator.PasGenerator.Result;
import static pasgenerator.PasGenerator.dlinnapass;
import static pasgenerator.PasGenerator.massSLat;


/**
 *
 * @author ĐŸĐµÑ‚Ñ€
 */
public class NewJFrame extends javax.swing.JFrame {
    public static Integer dlinnapass;
    
    FileDialog fdlg;
    javax.swing.JFileChooser fileChooser=new javax.swing.JFileChooser();
    /**
     * Creates new form NewJFrame
     */
    
    public NewJFrame() {
        initComponents();
    }
          
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setText("Цифры");
        jCheckBox1.setActionCommand("0..9");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("a..z");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jCheckBox3.setText("A..Z");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        jCheckBox4.setText("@,%...");
        jCheckBox4.setActionCommand("@%...");
        jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox4ActionPerformed(evt);
            }
        });

        jButton2.setText("генерировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "8", "9", "10", "11", "12" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBox5.setText("Исключить повторения символов");

        jCheckBox6.setText("а-я");
        jCheckBox6.setActionCommand("а..я");
        jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox6ActionPerformed(evt);
            }
        });

        jCheckBox7.setText("А-Я");
        jCheckBox7.setActionCommand("А..Я");
        jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox7ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Укажите длинну пароля.");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Проверка сложности пароля");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Выберите условия, которые будут");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("использоваться для генерации пароля.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                .addComponent(jCheckBox2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jCheckBox4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox7)
                            .addComponent(jCheckBox6)
                            .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox6)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jCheckBox5)
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(30, 30, 30))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox4ActionPerformed
    }//GEN-LAST:event_jCheckBox4ActionPerformed

    private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox6ActionPerformed
    }//GEN-LAST:event_jCheckBox6ActionPerformed

    private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox7ActionPerformed
    }//GEN-LAST:event_jCheckBox7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Integer Size = 0;
        Integer Result = 0;
        PasGenerator.massNumbers();
        PasGenerator.massSLatinica();
        PasGenerator.massBLatinica();
        PasGenerator.massSKirilica();
        PasGenerator.massBKirilica();
        PasGenerator.massSymbols();
        dlinnapass = Integer.parseInt ((String) jComboBox1.getSelectedItem());  //Đ±ĐµÑ€ĐµÑ‚ Đ¸Đ· jComboBox Đ´Đ»Đ¸Đ½Ñƒ Đ¼Đ°Ñ�Ñ�Đ¸Đ²Đ°
        String password = "";
        ArrayList ResultMass = new ArrayList();
        Integer Rand=0;
 
        if ((!jCheckBox1.isSelected()) &&  (!jCheckBox2.isSelected()) &&  (!jCheckBox3.isSelected()) &&
                 (!jCheckBox4.isSelected()) &&  (!jCheckBox5.isSelected()) &&  (!jCheckBox6.isSelected())){
        JOptionPane.showMessageDialog(rootPane, "Выберите условия!");
        }
        
        if (jCheckBox1.isSelected()){ 
        Size += 10;
        }
        if (jCheckBox2.isSelected()){
        Size += 26;
        }
        if (jCheckBox3.isSelected()){
        Size += 26;
        }
        if (jCheckBox6.isSelected()){
        Size += 33;
        }
        if (jCheckBox7.isSelected()){
        Size += 33;
        }
        if (jCheckBox4.isSelected()){
        Size += 26;
        }
        /*Đ¡Đ¾Ñ�Ñ‚Đ°Đ²Đ»Ñ�ĐµĐ¼ Đ°Đ»Ñ„Đ°Đ²Đ¸Ñ‚ */
        if (jCheckBox1.isSelected()){ 
        Result += 10;
        for (int i = 0; i<10;i++){
        ResultMass.add(PasGenerator.massNum[i]);//    ResultMass [i+Result] = PasGenerator.massNum [i];
        }
        }
        if (jCheckBox2.isSelected()){
        for (int i = 0; i<26; i++){
            ResultMass.add(PasGenerator.massSLat[i]);
        }
        Result += 26;
        }
        if (jCheckBox3.isSelected()){
        for (int i = 0; i<26; i++){
            ResultMass.add(PasGenerator.massBLat[i]);
        }
        Result += 26;
        }
        if (jCheckBox6.isSelected()){
        for (int i = 0; i<33; i++){
            ResultMass.add(PasGenerator.massSkirril[i]);
        }
        Result += 33;
        }
        if (jCheckBox7.isSelected()){
        for (int i = 0; i<33; i++){
            ResultMass.add(PasGenerator.massBkirril[i]);
        }
        Result += 33;
        }
        if (jCheckBox4.isSelected()){
        for (int i = 0; i<26; i++){
            ResultMass.add(PasGenerator.massSymb[i]);
        }
        Result += 26;
        }/**/
        System.out.println(ResultMass);
        
       
        
        
        Random random = new Random();
        Integer temp;
        if (jCheckBox5.isSelected()){
            if (ResultMass.size() < dlinnapass){
                JOptionPane.showMessageDialog(rootPane, "Генерация пароля невозможна.Измените условия!");
            }else{
        for (int i = 0;i<dlinnapass;i++){
            Rand = random.nextInt(ResultMass.size());           //Ñ�Đ»ÑƒÑ‡Đ°Đ¹Đ½Đ¾Đµ Ñ‡Đ¸Ñ�Đ»Đ¾, Đ´Đ»Ñ� Đ²Ñ‹Đ±Đ¾Ñ€ĐºĐ¸ Đ¸Đ· Ñ€ĐµĐ·Đ°Đ»Ñ‚Đ¼Đ°Ñ�Ñ�
            password += (ResultMass.get(Rand));                 //Đ·Đ°Đ¿Đ¾Đ»Đ½ĐµĐ½Đ¸Đµ Đ¼Đ°Ñ�Ñ�Đ¸Đ²Đ° Đ¿Đ°Ñ€Đ¾Đ»Ñ� Ñ�Đ»ÑƒÑ‡Đ°Đ¹Đ½Ñ‹Đ¼Đ¸ Ñ�Đ¸Đ¼Đ²Đ¾Đ»Đ°Đ¼Đ¸

            ResultMass.remove(ResultMass.get(Rand));

        }ResultMass.remove(Rand);//?
            }
        }else{
        for (int i=0;i<dlinnapass;i++){
            Rand = random.nextInt(ResultMass.size());           //Ñ�Đ»ÑƒÑ‡Đ°Đ¹Đ½Đ¾Đµ Ñ‡Đ¸Ñ�Đ»Đ¾, Đ´Đ»Ñ� Đ²Ñ‹Đ±Đ¾Ñ€ĐºĐ¸ Đ¸Đ· Ñ€ĐµĐ·Đ°Đ»Ñ‚Đ¼Đ°Ñ�Ñ�
            password += (ResultMass.get(Rand));                 //Đ·Đ°Đ¿Đ¾Đ»Đ½ĐµĐ½Đ¸Đµ Đ¼Đ°Ñ�Ñ�Đ¸Đ²Đ° Đ¿Đ°Ñ€Đ¾Đ»Ñ� Ñ�Đ»ÑƒÑ‡Đ°Đ¹Đ½Ñ‹Đ¼Đ¸ Ñ�Đ¸Đ¼Đ²Đ¾Đ»Đ°Đ¼Đ¸
        }
        }
        System.out.println(password);
        jTextField1.setText(password);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
    /*JFormattedTextField jTextField1;
    MaskFormatter formatter = null;
        try {
           formatter = new MaskFormatter("%H");
       } catch (java.text.ParseException exc) {
         // требуется ручное исключение
       }
    jTextField1 = new JFormattedTextField(formatter);*/
    }//GEN-LAST:event_jTextField1ActionPerformed

    //проверка сложности пароля
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        PasGenerator.massNumbers();
        PasGenerator.massSLatinica();
        PasGenerator.massBLatinica();
        PasGenerator.massSKirilica();
        PasGenerator.massBKirilica();
        PasGenerator.massSymbols();
        String str;
        Integer a=0,b=0,c=0,d=0,e=0;
        str = jTextField1.getText();
        char chislo[]=new char[dlinnapass];
        chislo = str.toCharArray();
        
        ArrayList ResultMass = new ArrayList();
        /*Đ¡Đ¾Ñ�Ñ‚Đ°Đ²Đ»Ñ�ĐµĐ¼ Đ°Đ»Ñ„Đ°Đ²Đ¸Ñ‚ */
        if (jCheckBox1.isSelected()){ 
        Result += 10;
        for (int i=0;i<dlinnapass;i++){
        for (int j = 0; j<10;j++){
        if(chislo[i]==PasGenerator.massNum[j]){
            a=1;
        }
        }
                }
        }
        if (jCheckBox2.isSelected()){
        for (int i=0;i<dlinnapass;i++){    
        for (int j = 0; j<26; j++){
            if(chislo[i]==PasGenerator.massSLat[i]){
            b=2;
        }
        }
        }
        }
        if (jCheckBox3.isSelected()){
        for (int i=0;i<dlinnapass;i++){    
        for (int j = 0; j<26; j++){
            if(chislo[i]==PasGenerator.massBLat[j]){
            c=2;
            }
            }
        }
        }
        if (jCheckBox6.isSelected() && jCheckBox7.isSelected()){
            e=2;
        }
        if (jCheckBox4.isSelected()){
        for (int i=0;i<dlinnapass;i++){    
        for (int j = 0; j<26; j++){
            if(chislo[i]==PasGenerator.massSymb[j]){
            d=2;    
            }
        }
        } 
        }
            
            /*if ((a==1) && (b==1) && (c==1) && (d==1) && (e==1)){
                JOptionPane.showMessageDialog(rootPane, "Сложный пароль");
                }*/
            if ((a+b+c+d+e)>5){
                JOptionPane.showMessageDialog(rootPane, "Сложный пароль");
                }
            if ((a+b+c+d+e)<5){
                JOptionPane.showMessageDialog(rootPane, "Простой пароль");
                }
            if ((a+b+c+d+e)==5){
                JOptionPane.showMessageDialog(rootPane, "Пароль средней сложности");
                }
                    
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}