/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graph;

import java.io.IOException;
import java.net.URLDecoder;

/**
 *
 * @author glebmillenium
 */
public class HelpFrame extends javax.swing.JFrame {

    /**
     * Creates new form HelpFrame
     */
    public HelpFrame() throws IOException {
        initComponents();
        String path = AGV.wayToJar();
        path = path.replaceAll("BuildGraphicProject.jar", "") + "/Data/help.html";
        //String htmlText = AGV.readFileAsString(path);
        
        jLabel.setText("<html>\n" +
"    <head>\n" +
"        <title>Описание используемых функций для построения графика</title>\n" +
"        <meta charset=\"UTF-8\">\n" +
"        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n" +
"    </head>\n" +
"    \n" +
"    <body BGCOLOR=\"#FFFACD\">\n" +
"        <div>\n" +
"        <table border=\"1\" cellspacing=\"0\" cellpadding=\"5\">\n" +
"        <tbody>\n" +
"        <tr>\n" +
"        <th>Свойство</th>\n" +
"        <th>Описание</th>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>E</tt></td>\n" +
"        <td>Основание натуральных логарифмов e.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>LN10</tt></td>\n" +
"        <td>Число ln 10.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>LN2</tt></td>\n" +
"        <td>Число ln 2.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>SQRT1_2</tt></td>\n" +
"        <td>Квадратный корень из 1/2.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>SQRT2</tt></td>\n" +
"        <td>Квадратный корень из 2.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <th>Метод</th>\n" +
"        <th>Описание</th>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>abs</tt></td>\n" +
"        <td>Возвращает модуль аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>arccos</tt></td>\n" +
"        <td>Возвращает арккосинус аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>arcsin</tt></td>\n" +
"        <td>Возвращает арксинус аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>arctg</tt></td>\n" +
"        <td>Возвращает арктангенс аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <tr>\n" +
"        <td><tt>sin</tt></td>\n" +
"        <td>Возвращает синус аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n"+
"        <td><tt>cos</tt></td>\n" +
"        <td>Возвращает косинус аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n"+
"        <td><tt>sc</tt></td>\n" +
"        <td>Возвращает секанс аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n"+
"        <td><tt>csc</tt></td>\n" +
"        <td>Возвращает косеканс аргумента.</td>\n" +
"        </tr>\n" +
"        <td><tt>tg</tt></td>\n" +
"        <td>Возвращает тангенс аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>ctg</tt></td>\n" +
"        <td>Возвращает котангенс аргумента</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>e</tt></td>\n" +
"        <td>Возвращает экспоненту аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>pow</tt></td>\n" +
"        <td>Возводит первый аргумент в степень, заданную вторым.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>sqrt</tt></td>\n" +
"        <td>Возвращает квадратный корень из аргумента.</td>\n" +
"        </tr>\n" +
"        <tr>\n" +
"        <td><tt>ln</tt></td>\n" +
"        <td>Возвращает натуральный логарифм аргумента.</td>\n" +
"        </tr>\n" +
"        </tbody>\n" +
"        </table>\n" +
"        </div>\n" +
"    </body>\n" +
"</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(650, 600));

        jLabel.setBackground(new java.awt.Color(237, 156, 76));
        jLabel.setFont(new java.awt.Font("Trebuchet MS", 2, 15)); // NOI18N
        jLabel.setText("Error! Не открылся HTML-скрипт.");
        jScrollPane1.setViewportView(jLabel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HelpFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
