package Graph;

import java.awt.*;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.script.ScriptException;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *  GraphFrame - графический класс, инициализирует пользовательский интерфейс
 *               путем создания объекта данного класса, через стандартный 
 *               (не расширенный) конструктор GraphFrame.
 * 
 *  @author Ан Глеб
 */
public class GraphFrame extends javax.swing.JFrame {

    /**
     *  Поля класса GraphFrame.
     * 
     *  private int delta   - 
     *  private int width   - ширина графика функции (по умолчанию 520)
     *  private int height  - высота графика функции (по умолчанию 520)
     *  private double step - шаг значения функции в один пиксель 
     *                        (масштаб графика)
     * 
     *  private JPanelGraph PanelGraph - Объект переопределенного графического
     *                                   пользовательского класса 
     *                                   типа PanelGraph
     *  private static java.util.List<JTextField> FieldsFunction - коллекция, 
     *          содержит функции(формулы) вводимые пользователем в TextField-ы
     */
    private int width = 520;
    private int height = 520;
    private double step = 0.05;
    private JPanelGraph PanelGraph = 
            new JPanelGraph(this.width, this.height, this.step);
    private static java.util.List<JTextField> FieldsFunction = 
            new ArrayList<JTextField>();
    private static java.util.List<JButton> ButtonsFunction = 
            new ArrayList<JButton>();
    private static java.util.List<Color> ColorsFunction = new ArrayList<Color>();
    private int delta = 0;
    private ShowColor ColorChoose = new ShowColor();
    
    /**
     * GraphFrame - конструктор графического класса, который инициализирует и 
     *              визуализирует графические компоненты вызываемого окна.
     * 
     * @param - отсуствуют
     */
    public GraphFrame() {
        initComponents();           //Вызов инициализаторов графических 
        paintGraphPanel(PanelGraph);//компонентов
        addTextField();             //Вывод Текстового поля для ввода функции
    }
    
    /**
     * Метод paintGraphPanel - вырисовывает дополнительные элемент, в котором
     *                         будет вырисовываться график функции
     * 
     * @param Graph 
     * @return void
     */
    public void paintGraphPanel(JPanelGraph Graph) {
            
        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(Graph);
        Graph.setLayout(jPanelLayout);
        Graph.setBackground(Color.white);
        jPanelLayout.setHorizontalGroup(
                jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addGap(0, this.width, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
                jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addGap(0, this.height, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(Graph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(157, Short.MAX_VALUE)
                        .addComponent(Graph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85))
        );

        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Button = new javax.swing.JButton();
        jButtonHelp = new javax.swing.JButton();
        jButtonFunction = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        text = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Button.setText("Построить!");
        Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonActionPerformed(evt);
            }
        });

        jButtonHelp.setText("Справка");
        jButtonHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHelpActionPerformed(evt);
            }
        });

        jButtonFunction.setBackground(java.awt.SystemColor.desktop);
        jButtonFunction.setText("Добавить функцию");
        jButtonFunction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFunctionActionPerformed(evt);
            }
        });

        jButton1.setBackground(java.awt.SystemColor.desktop);
        jButton1.setText("Удалить функцию");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        text.setText("f(x) =");

        jScrollPane1.setViewportView(JLabel);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("2D-график");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("3D-график");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(2, 2, 2)
                .add(text)
                .add(10, 10, 10)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 48, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jRadioButton1)
                    .add(jRadioButton2))
                .add(36, 36, 36)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jButtonFunction, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(38, 38, 38)
                        .add(jButtonHelp))
                    .add(Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 124, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonHelp)
                    .add(jButtonFunction, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(Button, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(text)))
                    .add(layout.createSequentialGroup()
                        .add(37, 37, 37)
                        .add(jRadioButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jRadioButton2)))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        AGV.windowClose(evt);
    }//GEN-LAST:event_formWindowClosing

    private void ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonActionPerformed
        String[] expression = new String[FieldsFunction.size()];
        Color[] colors = new Color[ButtonsFunction.size()];
        
        for(int i=0;i<FieldsFunction.size();i++)
        {
            expression[i]= FieldsFunction.get(i).getText();
            colors[i] = ButtonsFunction.get(i).getBackground();
        }
        
        try {
            PanelGraph.treatmentExpression(expression, colors);
            PanelGraph.drawGraph();
            
        } catch (ScriptException ex) {
            Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_ButtonActionPerformed

    private void jButtonHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHelpActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new HelpFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GraphFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }//GEN-LAST:event_jButtonHelpActionPerformed

    private void jButtonFunctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFunctionActionPerformed
        addTextField();
    }//GEN-LAST:event_jButtonFunctionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(FieldsFunction.size() > 1) {
            int index = FieldsFunction.size() - 1;
            JTextField field = FieldsFunction.remove(index);
            JButton button = ButtonsFunction.remove(index);
            JLabel.remove(field);
            JLabel.remove(button);
            this.delta-=25;
            JLabel.setPreferredSize(new Dimension(172,this.delta));
            JLabel.repaint();
            JLabel.revalidate();                   
        }  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addTextField(){
        JTextField field = new JTextField(" ");
        final JButton button = new JButton("...");
        ButtonsFunction.add(button);
        FieldsFunction.add(field);
        field.setAlignmentX(JButton.CENTER_ALIGNMENT);
        //field.setFont(font);
        field.setSize(150, 30);
        button.setSize(30, 30);
        button.setBackground(Color.black);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button.setBackground(ColorChoose.choose());
            }
        });
 
        field.setLocation(0, delta);
        button.setLocation(150, delta);
        this.delta+=25;
        JLabel.add(field);
        JLabel.add(button);
        JLabel.setPreferredSize(new Dimension(172,this.delta));
        JLabel.repaint();
        JLabel.revalidate();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphFrame().setVisible(true);
            }
        });
    }

    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button;
    private javax.swing.JLabel JLabel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonFunction;
    private javax.swing.JButton jButtonHelp;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables

}
